### ISSUE TITLE
How does `requests.Session()` speed up API calls?

### ISSUE THREAD

**Issue by TwilightMercy** [obfuscated-loop/plugin.video.fenda#2]
How does this commit speeds up Real Debrid?

https://github.com/obfuscated-loop/plugin.video.fenda/commit/9f454b43e66a70dbd26b24533b4ba4eb53c048a5

**Comment by obfuscated-loop** [comment]
Hi,

Each time you use `requests` directly, you are initializing a new session on each request. Using `requests.Session()`, we can reuse the same one and save a bit of time for each API call. At least that's how I think it works!

EDIT: It is basically a wrapper for the `Keep-Alive` header.

Thanks.

**Comment by TwilightMercy** [comment]
Thanks for the answer
Do you know to tell how great the speed increase is? asking out of curiosity
